
### Obtener todos los productos
GET http://localhost:3000/productos/

### Obtener un producto
GET http://localhost:3000/productos/66953d05693baf397055b328

### Crear un nuevo producto
POST http://localhost:3000/productos
Content-Type: application/json

{
          "nombre": "productoPrueba",
          "descripcion": "descripcionPrueba",
          "importe_compra": 1000,
          "importe_venta": 2000,
          "stock": 5
}

### Modificar un producto (completo)
PUT http://localhost:3000/productos/66953d05693baf397055b328
Content-Type: application/json

{
          "nombre": "productoModificado",
          "descripcion": "descripcionModificada",
          "importe_compra": 1500,
          "importe_venta": 3000,
          "stock": 40
}

### Modificar un producto (parcial)
PATCH http://localhost:3000/productos/66953d05693baf397055b328
Content-Type: application/json

{
          "nombre": "productoModificadoConPath",
          "descripcion": "descripcionModificadaConPath"
}


### Borrar un producto
DELETE http://localhost:3000/productos/66953d05693baf397055b328
