
### Obtener todas las ventas
GET http://localhost:3000/ventas/

### Obtener una venta
GET http://localhost:3000/ventas/66fd75a4c502625cc64a7070

### Crear una nueva venta
POST http://localhost:3000/ventas
Content-Type: application/json

{
    "estado": "En proceso",
    "fechaContacto": "2024-08-15",
    "fechaDeVenta": "2024-09-03",
    "fechaEntrega": "2024-09-10",
    "fechaCancelacion": null,
    "clienteId": "672daac323a2c9f8e48eabc3",
    "productoIds": ["672daac323a2c9f8e48eabc4", "672daac323a2c9f8e48eabc5"],
    "servicioIds": ["672daac323a2c9f8e48eabc6"]
}

### Modificar una venta (completo)
PUT http://localhost:3000/ventas/669874787690bc5f60d711fd
Content-Type: application/json

{
    "estado": "Finalizada",
    "fechaContacto": "2024-08-16",
    "fechaDeVenta": "2024-09-03",
    "fechaEntrega": "2024-09-10",
    "fechaCancelacion": null,
    "clienteId": "672daac323a2c9f8e48eabc3",
    "productoIds": ["672daac323a2c9f8e48eabc4"],
    "servicioIds": []
}

### Modificar una venta (parcial)
PATCH http://localhost:3000/ventas/669874787690bc5f60d711fd
Content-Type: application/json

{
    "estado": "Cancelada",
    "fechaCancelacion": "2024-09-05"
}

### Borrar una venta
DELETE http://localhost:3000/ventas/669878c25647790e562e97a5