
### Obtener todos los clientes
GET http://localhost:3000/clientes/

### Obtener un cliente
GET http://localhost:3000/clientes/672daac323a2c9f8e48eabc3

### Crear un nuevo cliente
POST http://localhost:3000/clientes
Content-Type: application/json

{
          "nombre": "Ignacio",
          "apellido":"Ramirez",
          "dni":"111111111",
          "mail":"ig@com.ar",
          "telefono":"111111111",
          "direccion":"calle falsa 123",
          "razon_social":"Mesa 12",
          "usuario":"usuario",
          "contraseña":"contraseña"
}

### Modificar un cliente (completo)
PUT http://localhost:3000/clientes/
Content-Type: application/json

{
          "nombre": "Constanza",
          "apellido":"Dominio",
          "dni":"22222222",
          "mail":"co@com.ar",
          "telefono":"22222222",
          "direccion":"calle falsa 144",
          "razon_social":"Mesa 10",
          "usuario":"UsuarioNacho",
          "razon_social":"contraseña"
}

### Modificar un cliente (parcial)
PATCH http://localhost:3000/clientes/
Content-Type: application/json

{
          "nombre": "Milton",
          "apellido":"Sarkissian",
          "dni":"111111111",
          "mail":"ig@test.com.ar",
          "telefono":"111111111",
          "direccion":"calle falsa 123",
          "razon_social":"Mesa 14"
}


### Borrar un cliente
DELETE http://localhost:3000/clientes/67344f5e59445f2f96ef54b4