
### Obtener todas las localidades
GET http://localhost:3000/localidades/

### Obtener una localidad
GET http://localhost:3000/localidades/66fc0fabab7a3de70a7bd902

### Crear una nueva localidad
POST http://localhost:3000/localidades
Content-Type: application/json

{
          "nombre": "Santa_fe",
          "codigo_postal":"2000"
}

### Modificar una localidad (completa)
PUT http://localhost:3000/localidades/66fc0fabab7a3de70a7bd902
Content-Type: application/json

{
          "nombre": "Cordoba",
          "codigo_postal":"2001"
}

### Modificar una localidad (parcial)
PATCH http://localhost:3000/localidades/66fc0fabab7a3de70a7bd902
Content-Type: application/json

{
          "nombre": "Cordoba",
          "codigo_postal":"2002"
}


### Borrar una localidad
DELETE http://localhost:3000/localidades/66fc0fabab7a3de70a7bd902
