
### Obtener todos los localidades
GET http://localhost:3000/localidades/

### Obtener un producto
GET http://localhost:3000/localidades/669456b15ef6e6df19e153e2

### Crear un nuevo producto
POST http://localhost:3000/localidades
Content-Type: application/json

{
          "nombre": "Santa_fe",
          "codigo_postal":"2000",
}

### Modificar un producto (completo)
PUT http://localhost:3000/localidades/669456b15ef6e6df19e153e2
Content-Type: application/json

{
          "nombre": "Santa_fe_mod",
          "codigo_postal":"2001",
}

### Modificar un producto (parcial)
PATCH http://localhost:3000/localidades/669456b15ef6e6df19e153e2
Content-Type: application/json

{
          "nombre": "Santa_fe_mod_path",
          "codigo_postal":"2002_mod_path",
}


### Borrar un producto
DELETE http://localhost:3000/localidades/669456b15ef6e6df19e153e2
